config/routes.rb
Rails.application.routes.draw do


  get 'transferts/new'

  devise_for :users
  root to: 'pages#home'

  resources :pages do
    get 'compte'
    get 'compoteste'
    resources :services
      resources :membres do
        get 'addphoto'
        get 'bravo'
        get 'profilecreation'
        get 'adressedelivraison'
        resources :paiements
        resources :pockets
        resources :transferts
      end
  end
  resources :kids do
    resources :pay4mes
    resources :ask_for_dollars
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask_for_dollar.rb
class AskForDollar < ApplicationRecord
  belongs_to :membre
  # mount_uploader :photo, PhotoUploader

end

app/models/ask_for_money.rb
class AskForMoney < ApplicationRecord
  belongs_to :membre
  mount_uploader :photo, PhotoUploader
end

app/models/ask_service.rb
class AskService < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :membre
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :family_pockets
  has_many :pockets, through: :family_pockets

  has_many :user_families

end

app/models/family_poche.rb
class FamilyPoch < ApplicationRecord
  belongs_to :family
  belongs_to :poch
end

app/models/family_pocket.rb
class FamilyPocket < ApplicationRecord
  belongs_to :family
  belongs_to :pocket
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :user_members
  has_many :members, throug: :user_members
end

app/models/membre.rb
class Membre < ApplicationRecord
  has_many :user_membres
  has_many :users, through: :user_membres

  has_many :membre_paiements
  has_many :paiements, through: :membre_paiements

  has_many :transferts
  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :ask_for_dollars

  has_many :ask_services
  has_many :services, through: :ask_services

  mount_uploader :photo, PhotoUploader

  MOIS = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"]

  def name
    fisrt_name
  end
end

app/models/membre_paiement.rb
class MembrePaiement < ApplicationRecord
  belongs_to :membre
  belongs_to :paiement
end

app/models/paiement.rb
class Paiement < ApplicationRecord
  has_many :membre_paiements
  has_many :membres, through: :membre_paiements


end

app/models/poch.rb
class Poch < ApplicationRecord

  has_many :family_pochs
  has_many :families, through: :family_pochs

end

app/models/poche.rb
class Poche < ApplicationRecord
  has_many :family_poches

end

app/models/pocket.rb
class Pocket < ApplicationRecord
  has_many :family_pockets
  has_many :user_pockets
  has_many :transferts


end

app/models/service.rb
class Service < ApplicationRecord
  has_many :ask_services
  has_many :users, through: :ask_services
  has_many :membres, through: :ask_services

  HOUR = Time.now.hour.to_s
  MINUTE = Time.now.min.to_s

end

app/models/transfert.rb
class Transfert < ApplicationRecord
  belongs_to :user
  belongs_to :membre
  belongs_to :pocket

  FREQUENCES = ["Par mois", "Par semaine", "Par jours"]
  validates :frequence, inclusion: {in: FREQUENCES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_families
  has_many :families, through: :user_families

  has_many :user_membres
  has_many :membres, through: :user_membres

  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :transferts

  has_many :ask_services
  has_many :services, through: :ask_services

end

app/models/user_family.rb
class UserFamily < ApplicationRecord
  belongs_to :user
  belongs_to :family
end

app/models/user_member.rb
class UserMember < ApplicationRecord
  belongs_to :user
  belongs_to :member
end

app/models/user_membre.rb
class UserMembre < ApplicationRecord
  belongs_to :user
  belongs_to :membre
end

app/models/user_pocket.rb
class UserPocket < ApplicationRecord
  belongs_to :user
  belongs_to :pocket
  belongs_to :membre
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :create, :new, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = @user.services
  end

  # GET /services/1
  # GET /services/1.json
  def show

  end

  # GET /services/new
  def new
    @as = AskService.new
    @service = Service.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

      if @service.save
        @membres = Membre.where(id: params[:ask_service][:membre_id])
        raise
        @membres.each do |membre|
          @as = AskService.new
          @as.user = @user
          @as.membre = membre
          @as.service = @service
          @as.save
        end
        redirect_to page_service(@user, @service)
      else
        render :new
      end

  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.js {render inline: "location.reload();" }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:description, :amout, :hour, :minute, :accepted, :has_been_done)
    end
end

app/views/services/_form.html.erb
<%= simple_form_for @service, url: page_services_path(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="service_description">
      <label class="left border-bottom" for="service_description">Objectif de la mission</label>
      <textarea placeholder="Une liste de course? Un lieu? Donnez à votre enfant un maximum d'information sur la mission." class="form-control text optional" name="service[description]" id="service_description"></textarea>
    </div>
    <div class="hidden range-container">
      <div class="row">
        <div class="center">
          <h5>40€</h5>
        </div>
      </div>
      <p class="range-field col-xs-12 my-range">
        <input aria-required="true" name="service[amount]" type="range" id="test3" min="0" max="150" />
      </p>
    </div>

    <div class="row hidden ">
      <div class="col s6">
        <%= f.input :hour, collection: (0..24), prompt: Service::HOUR %>
      </div>
      <div class="col s6">
        <%= f.input :minute, collection: (0..60), prompt: Service::MINUTE %>
      </div>
    </div>
    <div class="hidden">
      <%= simple_form_for @as, url: page_services_path(@user) do |f| %>
        <div class="row">
          <label class="left col s12">Pour qui sera la mission ?</label>
          <input type="hidden" name="ask_service[membre_id][]" value="">
        </div>
        <div class="row">
          <% @user.membres.each do |membre| %>
            <div class="col s6">
              <input type="checkbox" class="hidden" value="<%= membre.id %>" name="ask_service[membre_ids][]" id="  ask_service_ids_<%= membre.id %>">
              <label for="ask_service_ids_<%= membre.id %>">
                <%= image_tag 'teen.jpg',width: 100, height: 100, class: 'z-depth-5 circle' %>
              </label>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


<!-- inputs -->
  <div id="show-2" class="row hidden">
    <input type="submit" name="commit" value="ask" class="btn btn-large btn-floating right btn-floating green accent-3" data-disable-with="Create Ask for money">

    <div class="back left come-back">
      <i class="material-icons">arrow_left</i>Retour
    </div>

    <a id="show-1" class=" btn-floating btn-large waves-effect waves-light right black">
      <i class="material-icons">chevron_right</i>
    </a>
  </div>
<% end %>
<% end %>
<!-- Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa natus perferendis neque eaque architecto corporis iusto totam? Exercitationem illo iusto similique accusamus praesentium veniam error, voluptas, dolore nulla quas magni?
 -->

app/views/services/_new.html.erb
<div class="container-ask">
  <div class="background-circle">

  </div>
  <div class="ask-container">
    <div class="row">

      <p class="right" style="font-size: 30px" >Pay4me</p>
    </div>

      <%= simple_form_for @service, url: page_services_path(@user) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">

        <div class="service_description">
          <label class="left border-bottom" for="service_description">Objectif de la mission</label>
          <textarea placeholder="Une liste de course? Un lieu? Donnez à votre enfant un maximum d'information sur la mission." class="form-control text optional" name="service[description]" id="service_description"></textarea>
        </div>

        <div class="service-range-container">
          <div class="row">
            <div  class="center">
              <h5>Il aura 30€ pour sa mission</h5>
            </div>
          </div>
          <p style="top: 50px" class="range-field col-xs-12 my-range">
            <input aria-required="true" name="service[amount]" type="range" id="test3" min="0" max="150" />
          </p>
          <br>
          <div class="until row">
            <h6>Validation et réalisation de la mission jusqu'à :</h6>
            <div class="col s5">
              <select class="form-control select optional" name="service[hour]" id="service_hour">
                <%= (0...24).to_a.each do |min|%>
                <option value="<%= min %>"><%= min %></option>
                <% end %>
              </select>
            </div>
            <div class="col s5">
              <select class="form-control select optional" name="service[minute]" id="service_minute">
                <%= (0...60).to_a.each do |min|%>
                <option value="<%= min %>"><%= min %></option>
                <% end %>
              </select>
            </div>
          </div>
        </div>

        <div id="aqui">
          <%= simple_form_for @as, url: page_services_path(@user) do |f| %>
            <div class="row">
              <label class="left col s12">Pour qui sera la mission ?</label>
              <input type="hidden" name="ask_service[membre_id][]" value="">
            </div>
            <div class="row">
              <% @user.membres.each do |membre| %>
                <div class="col s6">
                  <input type="checkbox" class="hidden" value="<%= membre.id %>" name="ask_service[membre_ids][]" id="  ask_service_ids_<%= membre.id %>">
                  <label for="ask_service_ids_<%= membre.id %>">
                    <%= image_tag 'teen.jpg',width: 100, height: 100, class: 'z-depth-5 circle' %>
                  </label>
                </div>
              <% end %>
            </div>
          </div>

        </div>


    <!-- inputs -->
      <div class="row">
        <div class="back left come-back">
          <i class="material-icons">arrow_left</i>Retour
        </div>

        <div id="show-1" >
          <a class=" btn-floating btn-large waves-effect waves-light right black">
            <i class="material-icons">chevron_right</i>
          </a>
        </div>

        <a id="show-2" class=" btn-floating btn-large waves-effect waves-light right black">
            <i class="material-icons">chevron_right</i>
          </a>
        </div>

        <div id="show-3" >
          <input type="submit" name="commit" value="OK" class="btn btn-large btn-floating right btn-floating green accent-3" data-disable-with="Create Ask for money">
        </div>


      </div>
    </div>

    <% end %>
    <% end %>
  </div>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Amout</th>
      <th>Hour</th>
      <th>Minute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.description %></td>
        <td><%= service.amout %></td>
        <td><%= service.hour %></td>
        <td><%= service.minute %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.js.erb
jQuery(document).ready(function($) {
  var modal = $("<%= escape_javascript(render 'services/new') %>");

  modal.appendTo("body").animate(
    {
      top: 0
    },
    200
  );
  $("#show-2").hide();
  $("#show-3").hide();
  $("#aqui").hide();
  $(".service-range-container").hide();

  $("#show-1").click(function() {
    $("#show-1").hide();
    $("#show-2").fadeIn();

    $(".service_description").fadeOut();
    $(".service-range-container").fadeIn();
  });

  $("#show-2").click(function() {
    $("#show-2").fadeOut();
    $(".service-range-container").fadeOut();
    $("#aqui").fadeIn();
    $("#show-3").fadeIn();
  });
});

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Amout:</strong>
  <%= @service.amout %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @service.hour %>
</p>

<p>
  <strong>Minute:</strong>
  <%= @service.minute %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>