config/routes.rb
Rails.application.routes.draw do


  get 'transferts/new'

  devise_for :users
  root to: 'pages#home'

  resources :pages do
    get 'compte'
    get 'compoteste'
    resources :services
      resources :membres do
        get 'addphoto'
        get 'bravo'
        get 'profilecreation'
        get 'adressedelivraison'
        resources :paiements
        resources :pockets
        resources :transferts
      end
  end
  resources :kids do
    resources :pay4mes
    resources :ask_for_dollars
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask_for_dollar.rb
class AskForDollar < ApplicationRecord
  belongs_to :membre
  # mount_uploader :photo, PhotoUploader

end

app/models/ask_for_money.rb
class AskForMoney < ApplicationRecord
  belongs_to :membre
  mount_uploader :photo, PhotoUploader
end

app/models/ask_service.rb
class AskService < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :membre
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :family_pockets
  has_many :pockets, through: :family_pockets

  has_many :user_families

end

app/models/family_poche.rb
class FamilyPoch < ApplicationRecord
  belongs_to :family
  belongs_to :poch
end

app/models/family_pocket.rb
class FamilyPocket < ApplicationRecord
  belongs_to :family
  belongs_to :pocket
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :user_members
  has_many :members, throug: :user_members
end

app/models/membre.rb
class Membre < ApplicationRecord
  has_many :user_membres
  has_many :users, through: :user_membres

  has_many :membre_paiements
  has_many :paiements, through: :membre_paiements

  has_many :transferts
  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :ask_for_dollars

  has_many :ask_services
  has_many :services, through: :ask_services

  mount_uploader :photo, PhotoUploader

  MOIS = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"]

  def name
    fisrt_name
  end
end

app/models/membre_paiement.rb
class MembrePaiement < ApplicationRecord
  belongs_to :membre
  belongs_to :paiement
end

app/models/paiement.rb
class Paiement < ApplicationRecord
  has_many :membre_paiements
  has_many :membres, through: :membre_paiements


end

app/models/poch.rb
class Poch < ApplicationRecord

  has_many :family_pochs
  has_many :families, through: :family_pochs

end

app/models/poche.rb
class Poche < ApplicationRecord
  has_many :family_poches

end

app/models/pocket.rb
class Pocket < ApplicationRecord
  has_many :family_pockets
  has_many :user_pockets
  has_many :transferts


end

app/models/service.rb
class Service < ApplicationRecord
  has_many :ask_services
  has_many :users, through: :ask_services
  has_many :membres, through: :ask_services

  HOUR = Time.now.hour.to_s
  MINUTE = Time.now.min.to_s

end

app/models/transfert.rb
class Transfert < ApplicationRecord
  belongs_to :user
  belongs_to :membre
  belongs_to :pocket

  FREQUENCES = ["Par mois", "Par semaine", "Par jours"]
  validates :frequence, inclusion: {in: FREQUENCES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_families
  has_many :families, through: :user_families

  has_many :user_membres
  has_many :membres, through: :user_membres

  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :transferts

  has_many :ask_services
  has_many :services, through: :ask_services

end

app/models/user_family.rb
class UserFamily < ApplicationRecord
  belongs_to :user
  belongs_to :family
end

app/models/user_member.rb
class UserMember < ApplicationRecord
  belongs_to :user
  belongs_to :member
end

app/models/user_membre.rb
class UserMembre < ApplicationRecord
  belongs_to :user
  belongs_to :membre
end

app/models/user_pocket.rb
class UserPocket < ApplicationRecord
  belongs_to :user
  belongs_to :pocket
  belongs_to :membre
end

app/controllers/membres_controller.rb
class MembresController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_user
  before_action :set_membre, only: [:show, :update]

  def index
    @family = @user.membres
    @pockets = @user.pockets
  end

  def compoteste
    @membre = Membre.find(params[:membre_id])
  end

  def show
  end

  def adressedelivraison
    @membre = Membre.find(params[:membre_id])
  end

  def bravo
    @membre = Membre.find(params[:membre_id])

  end

  def addphoto
    @membre = Membre.find(params[:membre_id])
  end

  def profilecreation
    @membre = Membre.find(params[:membre_id])
    @paiement = Paiement.new
  end

  def new
    @membre = Membre.new
    @usermembre = UserMembre.new
  end

  def create
    @membre = Membre.new(membre_params)
    @usermembre = UserMembre.new
    @usermembre.user = @user
    @usermembre.membre = @membre
    @usermembre.save
    if @membre.save
      redirect_to new_page_membre_pocket_path(@user, @membre.id)
    else
      render :new
    end

  end

  def compte
    @membre = Membre.find(params[:membre_id])

  end

  def edit
  end

  def update
    @membre.update(membre_params)
    redirect_to page_membre_path(@user, @membre)
  end

  private
  def set_membre
    @membre = Membre.find(params[:id])
  end
  def set_user
    @user = current_user
  end

  def membre_params
    params.require(:membre).permit(:phone_numbre, :sexe, :last_name, :fisrt_name, :birthday, :photo)
  end
end

app/views/membres/_button.html.erb
<div class="fixed-action-btn click-to-toggle" id="faButton" >
  <a class="btn-floating btn-large red">
  <i class="large material-icons">mode_edit</i>
  </a>

  <ul>
    <!-- premier bouton -->
    <li>
      <a class="btn-floating red">
        <i class="material-icons">insert_chart</i>
        <p>teste</p>
      </a>
    </li>
    <!-- second bouton -->
    <li>
      <a class="btn-floating yellow darken-1">
        <i class="material-icons">format_quote</i>
      </a>
    </li>
    <!-- troisème bouton -->
    <li>
      <a class="btn-floating green">
        <i class="material-icons">publish</i>
      </a>
    </li>
    <!-- quatrième bouton -->
    <li>
      <a class="btn-floating blue">
        <i class="material-icons">attach_file</i>
      </a>
    </li>

  </ul>

</div>

app/views/membres/_tranfert.html.erb
<div class="container-new">
  <div class="card">
      <%= image_tag 'arrow', height: 20, class: 'card-arrow' %>
      <%= image_tag 'cross', height: 15, class: 'cross' %>
    <div class="annonce" id="new-membrer-header" ><h1>Programmer <br> un versement</h1>
        <%= image_tag 'pagination', height: 10, class: 'pagination-pics' %>
    </div>
    <div class="card-user" >
      <%= image_tag 'photo', height: 40 , class: 'camera'%>
    </div>
  </div>



</div>

app/views/membres/addphoto.html.erb
<div class="first-name-container">
  <p><%= Membre.last.fisrt_name%></p>
  <div class="undername" ></div>
</div>

<%= simple_form_for @membre, url: page_membre_path(@user, @membre) do |f| %>

  <div class="container-bulle">
    <%= image_tag 'poche_blanche.png', height:180 %>
  </div>

  <!-- Uploader -->
  <div class="container-bulle">
  <h3>Choisssez la photo de votre enfant</h3>
      <label for="membre_photo">
        <%= image_tag 'photo.png' %>
      </label>
      <input class="hidden" type="file" name="membre[photo]" id="membre_photo">
  </div>


  <!-- button -->

    <div class="row">
      <input class="btn-floating btn-large waves-effect waves-light black" type="submit">
        <a class="btn-floating btn-large waves-effect waves-light black">
          <i class="material-icons">arrow_forward</i>
        </a>
      </input>
    </div>
    <%= link_to 'Back', 'javascript:history.back()' %>
    <a href="new"><i class="material-icons">arrow_back</i>retour</a>

<% end %>

app/views/membres/adressedelivraison.html.erb
<div class="grey-b">

  <div class="header-profilecreation">
    <div class="col s10">
      <div class="header-profilecreation-name">
       <h4><%= @membre.fisrt_name %>Raphael</h4>
      </div>
    </div>
    <div class="header-profilecreation-photo col s2">
      <%= image_tag 'teen.jpg', height: 40, width: 40, class: "img-circle"%>
    </div>

  </div>

  <div class="container-poche-creation">
    <div style="margin: 0 auto" id="test1" class="pocket">
      <%= image_tag 'visa-card.png', class: 'vise-pics' %>
    </div>
  </div>
</div>


<div class="main-container-profilecreation">
  <div class="content-profilecreation">
    <h3 style="margin: 20px;
    font-size: 20px;" >Entrez l'adresse de livraison</h3>
    <h5>Pour recevoir la carte Family Wallet de Raphäel</h5>
  </div>



  <div style="bottom: -60px;" class="footer-buttons">
    <div class="left">
    <a href="javascript:history.back()">
      <i class="material-icons">arrow_back</i>retour
    </a>
    </div>
  </div>

</div>

app/views/membres/bravo.html.erb
<div class="main-container-profilecreation">

  <div class="header-profilecreation">
    <div class="col s10">
      <div class="header-profilecreation-name">
       <h4><%= @membre.fisrt_name %>Raphael</h4>
      </div>
    </div>
    <div class="header-profilecreation-photo col s2">
      <%= image_tag 'teen.jpg', height: 40, width: 40, class: "img-circle"%>
    </div>

  </div>

  <div class="container-poche-creation">
    <div style="margin: 0 auto" id="test1" class="pocket">
      <div class="pocket-name" >
        <p></p>
      </div>
      <div class="container-pocket-pics">
        <div class="right pocket-pics">
          <p></p>
        </div>
      </div>
    </div>
  </div>

  <div class="content-profilecreation" id="transferts-new-content">
    <h4>Félicitation,<br>vous avez crée <br>la poche<p class="pinky"><%= Pocket.last.name %></p></h4>

    <div style="margin-top: 60px"  class="row">
      <p>Souhaitez-vous lui en crer une autre ? </p>


      <div class="offset-s3 z-depth-2 ask-answer col s3">
        <span class="radio">
          <label for="ask_for_dollar_accepted_true">
            <input class="radio_buttons optional" type="radio" value="true" name="ask_for_dollar[accepted]" id="ask_for_dollar_accepted_true">
            <%= link_to new_page_membre_paiement_path(current_user, @membre) do  %>
            <p>Oui</p>
            <% end %>
          </label>
        </span>
      </div>
      <div class="col s1"></div>

      <div class="z-depth-2 ask-answer col s3">
        <span class="radio">
          <label for="ask_for_dollar_accepted_false">
            <input class="radio_buttons optional" readonly="readonly" type="radio" value="false" name="ask_for_dollar[accepted]" id="ask_for_dollar_accepted_false">
            <%= link_to new_page_membre_paiement_path(current_user, @membre) do  %>
            <p>Non</p>
            <i class="material-icons"></i>
            <% end %>
          </label>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/membres/compte.html.erb
<div class="first-name-container">
  <p><%= Membre.last.fisrt_name%></p>
  <div class="undername" ></div>
</div>


  <div class="container-bulle">
    <%= image_tag 'poche_photo.png', height:180 %>
  </div>



  <!-- button -->
    <div class="container-bulle">
      <h3> As t'il déja un compte en banque?</h3>
      <div class="row">

        <div class="col-xs-12">
            <%= link_to page_membre_path(@user, @membre) do %>
              <div class="compte-btn">
                <p>NON, JE LUI DÉDIE UNE BULLE SUR MON COMPTE</p>
              </div>
            <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <div class="compte-btn" id="identifiants">
            <p>OUI, JE RENTRE SES IDENTIFIANTS BANCAIRES</p>
          </div>
        </div>
      </div>

        <div class="container" id="toshow">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s6">
                <input id="icon_prefix" type="text" class="form-plus validate">
                <label for="icon_prefix">Identifiant</label>
              </div>
              <div class="input-field col s6">
                <input id="icon_telephone" type="tel" class="form-plus validate">
                <label for="icon_telephone">Mot de Passe</label>
              </div>

              <%= link_to page_membre_path(@user, @membre) do %>
                <div style="margin-left: 45%" class="waves-effect waves-light btn light-blue darken-4">VALIDER
                </div>
              <% end %>
            </div>
          </form>
        </div>




    </div>



    <%= link_to do %>
      <% 'javascript:history.back()' %>
      <i class="material-icons" id="blackarrow">arrow_backward</i>
    <% end %>

app/views/membres/edit.html.erb
edit membre

app/views/membres/index.html.erb
<% if @user.membres.empty? %>
  <p>Aucun Membre dans ma famille :-(</p>
  <div class="btn-checkboxe">
  <p>
  <%= link_to "Ajouter un Membre à ma famille", new_page_membre_path %>
  </p>
  </div>
<% else %>
  <div class="membre-container">

      <% @user.membres.each do |membre| %>
        <span class="btn-checkboxe">
          <%= link_to membre.fisrt_name.to_s, page_membre_path(@user,membre)  %>

        </span>
      <% end %>

  </div>
<div class="btn-checkboxe yellow">
  <p>

  <%= link_to "Ajouter un Membre", new_page_membre_path %>
  </p>
  </div>
    </div>
<% end %>
<hr>

app/views/membres/new.html.erb
<%= simple_form_for @membre, url: page_membres_path(@user) do |f| %>
<div class="main-container-profilecreation" id="membre-new" >

  <div class="container-bulle">
    <label class="center" for="ask_for_money_photo">
      <%= image_tag 'teen.jpg', height: 120, width: 120, class: "img-circle"%>
    <p style="margin: 20px; border-bottom: 2px solid black; font-weight: 600;">Raphaël</p>
    </label>
    <input class="hidden file optional" type="file" name="ask_for_money[photo]" id="ask_for_money_photo">
    <%= f.input :photo_cache, as: :hidden %>
  </div>


  <div class="content-profilecreation" id="membre-new" >
    <div class="form-inputs-new">
        <!-- First Name -->
      <!-- <div class="input-div-new">
        <div class="form-group string optional membre_last_name">
          <div class="input-field col s12">
            <input name="membre[fisrt_name]" id="membre_fisrt_name" type="text" class="form-control validate">
            <label for="fisrt_name">Prénom</label>
          </div>
        </div>
      </div>
      <!-- Last Name  -->
      <!-- <div class="input-div-new">
        <div class="form-group string optional membre_last_name">
          <div class="input-field col s12">
            <input name="membre[last_name]" id="membre_last_name" type="text" class="form-control validate">
            <label for="last_name">Nom</label>
          </div>
        </div>
      </div> -->

      <!-- Birthday -->
      <div style="margin-top: 100px" class="birthday-date">
        <div class="label-birthday">
          <p>Date de Naissance  </p>
        </div>
        <div class="membre_day">
          <select class="form-control select optional" name="membre[day]" id="membre_day">
            <option value=""><p>Jour</p></option>
            <% (1..31).to_a.each do |op| %>
              <option value="<%= op %>"><%= op %></option>
            <% end %>
          </select>
        </div>


        <div class="membre_month">
          <select class="form-control select optional" name="membre[month]" id="membre_month">
            <option value="">Mois</option>
            <% Membre::MOIS.each do |op| %>
            <option value="<%= op %>"><%= op %></option>
            <% end %>
          </select>
        </div>

        <div class="membre_year">
          <select class="form-control select optional" name="membre[year]" id="membre_year">
          <option value="">Année</option>
            <% (2000..2010).to_a.each do |op| %>
              <option value="<%= op %>"><%= op %></option>
            <% end %>
          </select>
        </div>
      </div>

      <div class="input-div-new">
        <div class="form-group string optional membre_birthday">
          <div class="input-field col s12">
            <input placeholder="+33 7 24 XX XX XX" name="membre[birthday]" id="membre_birthday" type="text" class="form-control validate">
            <label for="birthday">Numéro de téléphone</label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->

  <div class="footer-buttons">
    <div class="forward" >
        <input type="submit" name="commit" value="OK" class="btn btn-large btn-floating right btn-floating black accent-3" data-disable-with="Create Ask for money">

      </a>
    </div>
    <!--
    <div class="backward">
      <a href="javascript:history.back()">
        <i class="material-icons">arrow_back</i>
      </a>
    </div> -->
  </div>
</div>
<% end %>

app/views/membres/profilecreation.html.erb
<div class="main-container-profilecreation">

  <div class="header-profilecreation">
      <p>&#x2501; &nbsp;<%=@membre.fisrt_name%>&nbsp;  &#x2501;</p>
      <div class="chip left">
      <%= image_tag 'pomme.png' %>
      Pay
    </div>
    <div class="chip left">
      <%= image_tag 'mastercard.png'%>
      carte débit
    </div>
  </div>
  <div class="content-profilecreation">
    <h4>Choisisez ses modes de paiements</h4>
    <%= simple_form_for @paiement, url: page_membre_paiements_path do |f| %>
    <%= f.error_notification %>

      <div class="row">
        <div class="col s4">
          <span class="checkbox selected-mode" id="input-mode">
            <label for="paiement_mode_apple_pay">
              <input class="input-mode" type="checkbox" value="Apple Pay" name="paiement[mode][]" id="paiement_mode_apple_pay">
              <p>Apple Pay</p>
            </label>
          </span>
        </div>

        <div class="col s4">
          <span class="checkbox" id="input-mode">
            <label for="paiement_mode_paylib">
              <input class="input-mode" type="checkbox" value="Paylib" name="paiement[mode][]" id="paiement_mode_paylib">
              <p>Paylib</p>
            </label>
          </span>
        </div>

        <div class="col s4">
          <span class="checkbox selected-mode" id="input-mode">
            <label for="paiement_mode_carte_débit">
              <input class="input-mode" type="checkbox" value="Carte débit" name="paiement[mode][]" id="paiement_mode_carte_débit">
              <p>Carte débit</p>
            </label>
          </span>
        </div>
      </div>
      <div class="container-fluid ">
        <%= image_tag "carte_debit.png", height: 200 %>
        <h5>CHOISIR</h5>
      </div>

      <div class="container-fluid hide" id="carte-adresse">

        <div class="row">
          <div class="input-field col s12 form-plus">
            <input id="password" type="password" class="validate">
            <label for="password">Adresse 1</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12 form-plus">
            <input id="password" type="password" class="validate">
            <label for="password">Adresse 2</label>
          </div>
        </div>

        <div class="row">
          <div class="col s1"></div>

          <div class="input-field col s4 form-plus">
            <input id="password" type="password" class="validate">
            <label for="password">Code Postal</label>
          </div>

          <div class="col s2"></div>

          <div class="input-field col s4 form-plus">
            <input id="password" type="password" class="validate">
            <label for="password">Ville</label>
          </div>

        </div>


      </div>


  </div>

  <div class="footer-buttons">
    <div class="btn-floating right btn-large waves-effect waves-light black add" >
    <input type="submit" name="commit" value="&#x2794">

    </div>

    <a href="javascript:history.back()">
      <i class="material-icons">arrow_back</i>retour
    </a>
  </div>

    <% end %>
</div>

app/views/membres/show.html.erb
<div class="main-container-profilecreation">
  <div class="header-profilecreation">
    <div class="col s10">
      <div class="header-profilecreation-name">
       <h4><%= @membre.fisrt_name %></h4>
     </div>
   </div>
   <div class="header-profilecreation-photo col s2">
    <%= image_tag"teen.jpg", width: 40, height: 40, class: 'img-circle'%>
  </div>
</div>

<div class="content-profilecreation" id="content-show">
  <ul id="tabs-swipe-demo" class="tabs">
    <li class="tab col s3">
      <a href="#test-swipe-1">Ses Poches</a></li>
      <li class="tab col s3">
        <a class="active" href="#test-swipe-2">Ses Opérations</a>
      </li>
      <li class="tab col s3">
        <a href="#test-swipe-3">Sa carte</a>
      </li>
    </ul>

    <div id="test-swipe-1" class="vos-poches col s12">
      <div class="card-son-argent">
        <div class="card-son-argent-titre">
          <p style="color: black; font-weight: 600;">Son Argent de Poche</p>
        </div>
        <div class="card-son-argent-mois">
          <p>40€/mois</p>
        </div>
        <div class="card-son-argent-gain">
          <p>+155 €</p>
        </div>
        <div class="card-son-argent-arrow">
          <i class="material-icons">arrow_forward</i>
        </div>
      </div>
      <div class="vos-poches-versements">
        <h6>Vos poches versements</h6>
        <%= image_tag 'Virement_1.png', class: 'tapoche' %>
        <%= image_tag 'Virement_1_Argentdepoche.png', class: 'tapoche'  %>
        <%= image_tag 'Virement 2.png', class: 'tapoche'  %>
        <%= image_tag 'Virement_1.png', class: 'tapoche' %>

      </div>

      <div class="card-son-askmonay">
        <div class="card-son-askmonay-not">
          <p>AskMoney</p>
        </div>
        <div class="card-son-askmonay-titre">
          <p style="color: black; font-weight: 600;">Total des demandes</p>
        </div>
        <div class="card-son-askmonay-mois">
          <p>Dernière demande le 19/03/18</p>
        </div>
        <div class="card-son-askmonay-gain">
          <p>55€</p>
        </div>
        <div class="card-son-askmonay-arrow">
          <i class="material-icons">arrow_forward</i>
        </div>
      </div></div>

      <div id="test-swipe-2" class="opérations-container col s12">
        <div class="row">

          <div class="date">
            <h2>Aujoud'hui, à 12h23</h2>
          </div>
          <div class="bulle-alloue right">
            <p>Argent de Poche</p>
            <%= image_tag 'mini-poche-1.png', height: 15 %>
          </div>

          <div class="notification">
            <div class="debiteur">

              <div class="debiteur-logo">
                <%= image_tag "mcdonalds_logo.png", height: 42 %>
              </div>

              <div class="debiteur-name">
                <p>UGC</p>
              </div>

            </div>

            <div class="swith">
              <div class="to-swith left">
                <p>-7
                  <span>€</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">

          <div class="date">
            <h2>Hier, à 12h23</h2>
          </div>
          <div class="bulle-alloue right">
            <p>Piano</p>
            <%= image_tag 'poche_mini_4.png', height: 15 %>
          </div>

          <div class="notification">
            <div class="debiteur">

              <div class="debiteur-logo">
                <%= image_tag "mcdonalds_logo.png", height: 42 %>
              </div>

              <div class="debiteur-name">
                <p>Cours Piano</p>
              </div>

            </div>

            <div class="swith">
              <div class="to-swith left">
                <p>-20
                  <span>€</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">

          <div class="date">
            <h2>Hier, à 9h23</h2>
          </div>
          <div class="bulle-alloue right">
            <p>Arg de Poche</p>
            <%= image_tag 'mini-poche-1.png', height: 15 %>
          </div>

          <div class="notification">
            <div class="debiteur">

              <div class="debiteur-logo">
                <%= image_tag "mcdonalds_logo.png", height: 42 %>
              </div>

              <div class="debiteur-name">
                <p>Le Badaboum</p>
              </div>

            </div>

            <div class="swith">
              <div class="to-swith left">
                <p>-8,55
                  <span>€</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">

          <div class="date">
            <h2>Lundi, à 20h23</h2>
          </div>
          <div class="bulle-alloue right">
            <p>AskMoney</p>
            <%= image_tag 'poche_mini_3.png', height: 15 %>
          </div>

          <div class="notification">
            <div class="debiteur">

              <div class="debiteur-logo">
                <%= image_tag "mcdonalds_logo.png", height: 42 %>
              </div>

              <div class="debiteur-name">
                <p>Franprix</p>
              </div>

            </div>

            <div class="swith">
              <div class="to-swith left">
                <p>-57
                  <span>€</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">

          <div class="date">
            <h2>Vendredi, à 12h23</h2>
          </div>
          <div class="bulle-alloue right">
            <p>Déjeuner</p>
            <%= image_tag 'mini-poche-2.png', height: 15 %>
          </div>

          <div class="notification">
            <div class="debiteur">

              <div class="debiteur-logo">
                <%= image_tag "mcdonalds_logo.png", height: 42 %>
              </div>

              <div class="debiteur-name">
                <p>Mcdonald's</p>
              </div>

            </div>

            <div class="swith">
              <div class="to-swith left">
                <p>-12
                  <span>€</span>
                </p>
              </div>
            </div>
          </div>
        </div></div>

        <div id="test-swipe-3" class="col s12 sa-carte">
          <div class="carte-debit-container">
            <%= image_tag 'carte_debit.png', height: 100 %>
          </div>
          <div class="sa-carte-range" id="value-range" >
            <h2>Plafond de la carte</h2>
            <p id="plafond-carte-value">40€</p>
          </div>

          <div class="range-container">
            <p class="range-field col-xs-12 my-range">
              <input value="150" aria-required="true" name="transfert[value]" type="range" id="plafond-carte-slider" min="0" max="300" />
            </p>
          </div>

          <div class="sa-carte-paiement_roof">
            <label class="control-label select optional" for="paiement_roof"></label>
            <select class="browser-default" name="paiement[plafond]" id="paiement_plafond">
              <option value="Semaine">Par semaine</option>
              <option value="Mois">Par mois</option>
              <option value="Jour">Par jour</option>
            </select>
          </div>

          <div class="switch sa-carte-checkboxes">
            <p>Bloquer la carte</p>
            <label>
              <input type="checkbox">
              <span class="lever"></span>
            </label>
          </div></div>
        </div>
      </div>