config/routes.rb
Rails.application.routes.draw do


  get 'transferts/new'

  devise_for :users
  root to: 'pages#home'

  resources :pages do
    get 'compte'
    get 'compoteste'
    resources :services
      resources :membres do
        get 'addphoto'
        get 'bravo'
        get 'profilecreation'
        get 'adressedelivraison'
        resources :paiements
        resources :pockets
        resources :transferts
      end
  end
  resources :kids do
    resources :pay4mes
    resources :ask_for_dollars
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask_for_dollar.rb
class AskForDollar < ApplicationRecord
  belongs_to :membre
  # mount_uploader :photo, PhotoUploader

end

app/models/ask_for_money.rb
class AskForMoney < ApplicationRecord
  belongs_to :membre
  mount_uploader :photo, PhotoUploader
end

app/models/ask_service.rb
class AskService < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :membre
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :family_pockets
  has_many :pockets, through: :family_pockets

  has_many :user_families

end

app/models/family_poche.rb
class FamilyPoch < ApplicationRecord
  belongs_to :family
  belongs_to :poch
end

app/models/family_pocket.rb
class FamilyPocket < ApplicationRecord
  belongs_to :family
  belongs_to :pocket
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :user_members
  has_many :members, throug: :user_members
end

app/models/membre.rb
class Membre < ApplicationRecord
  has_many :user_membres
  has_many :users, through: :user_membres

  has_many :membre_paiements
  has_many :paiements, through: :membre_paiements

  has_many :transferts
  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :ask_for_dollars

  has_many :ask_services
  has_many :services, through: :ask_services

  mount_uploader :photo, PhotoUploader

  MOIS = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"]

  def name
    fisrt_name
  end
end

app/models/membre_paiement.rb
class MembrePaiement < ApplicationRecord
  belongs_to :membre
  belongs_to :paiement
end

app/models/paiement.rb
class Paiement < ApplicationRecord
  has_many :membre_paiements
  has_many :membres, through: :membre_paiements


end

app/models/poch.rb
class Poch < ApplicationRecord

  has_many :family_pochs
  has_many :families, through: :family_pochs

end

app/models/poche.rb
class Poche < ApplicationRecord
  has_many :family_poches

end

app/models/pocket.rb
class Pocket < ApplicationRecord
  has_many :family_pockets
  has_many :user_pockets
  has_many :transferts


end

app/models/service.rb
class Service < ApplicationRecord
  has_many :ask_services
  has_many :users, through: :ask_services
  has_many :membres, through: :ask_services

  HOUR = Time.now.hour.to_s
  MINUTE = Time.now.min.to_s

end

app/models/transfert.rb
class Transfert < ApplicationRecord
  belongs_to :user
  belongs_to :membre
  belongs_to :pocket

  FREQUENCES = ["Par mois", "Par semaine", "Par jours"]
  validates :frequence, inclusion: {in: FREQUENCES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_families
  has_many :families, through: :user_families

  has_many :user_membres
  has_many :membres, through: :user_membres

  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :transferts

  has_many :ask_services
  has_many :services, through: :ask_services

end

app/models/user_family.rb
class UserFamily < ApplicationRecord
  belongs_to :user
  belongs_to :family
end

app/models/user_member.rb
class UserMember < ApplicationRecord
  belongs_to :user
  belongs_to :member
end

app/models/user_membre.rb
class UserMembre < ApplicationRecord
  belongs_to :user
  belongs_to :membre
end

app/models/user_pocket.rb
class UserPocket < ApplicationRecord
  belongs_to :user
  belongs_to :pocket
  belongs_to :membre
end

app/controllers/ask_for_dollars_controller.rb
class AskForDollarsController < ApplicationController
  before_action :set_ask_for_dollar, only: [:show, :edit, :update, :destroy]

  # GET /ask_for_dollars
  # GET /ask_for_dollars.json
  def index
    @kid = Membre.find(params[:kid_id])
    @ask_for_dollars = AskForDollar.all
  end

  # GET /ask_for_dollars/1
  # GET /ask_for_dollars/1.json
  def show
    @membre = Membre.find(params[:kid_id])
  end

  # GET /ask_for_dollars/new
  def new
    @ask_for_dollar = AskForDollar.new
    @membre = Membre.find(params[:kid_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /ask_for_dollars/1/edit
  def edit
  end

  # POST /ask_for_dollars
  # POST /ask_for_dollars.json
  def create
    @ask_for_dollar = AskForDollar.new(ask_for_dollar_params)
    @membre = Membre.find(params[:kid_id])
    @ask_for_dollar.membre = @membre
    if @ask_for_dollar.save
      redirect_to kid_path(@membre)
    else
      render :new
    end

  end

  # PATCH/PUT /ask_for_dollars/1
  # PATCH/PUT /ask_for_dollars/1.json
  def update

    if @ask_for_dollar.update(ask_for_dollar_params)
      redirect_to kid_path(@membre)
    else
      render :edit
    end
  end

  # DELETE /ask_for_dollars/1
  # DELETE /ask_for_dollars/1.json
  def destroy
    @ask_for_dollar.destroy
    respond_to do |format|
      format.html { redirect_to ask_for_dollars_url, notice: 'Ask for dollar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ask_for_dollar
      @ask_for_dollar = AskForDollar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ask_for_dollar_params
      params.require(:ask_for_dollar).permit(:credit, :description, :object, :accepted, :has_been_reed)
    end
end

app/views/ask_for_dollars/_form.html.erb
<%= simple_form_for(@ask_for_dollar) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :credit %>
    <%= f.input :description %>
    <%= f.input :object %>
    <%= f.input :accepted %>
    <%= f.input :has_been_reed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ask_for_dollars/_new.html.erb
<div class="container-ask">
  <div class="background-circle">

  </div>
  <div class="ask-container">
    <div class="row">

      <p class="left" style="font-size: 30px" >AskMoney</p>
    </div>

    <%= simple_form_for @ask_for_dollar, url: kid_ask_for_dollars_path(@membre) do |f| %>
      <div id="show-1">
        <!-- Crédit -->
        <div class="input-field form-group string optional ask_for_dollar_credit">
          <label class="control-label string optional" for="ask_for_money_credit">De combien as-tu besoin?</label>
          <input class="form-control string optional" type="text" name="ask_for_dollar[credit]" id="ask_for_dollar_credit">
        </div>
        <!-- Objet -->
        <div class="input-field form-group string optional ask_for_dollar_object">
          <label class="control-label string optional" for="ask_for_dollar_object">Pour acheter quoi ? </label>
          <input class="form-control string optional" type="text" name="ask_for_dollar[object]" id="ask_for_dollar_object">
        </div>
      </div>
      <!-- add photo -->
      <div class="row">
        <div class="form-group file optional ask_for_money_photo">
          <label class=" left control-label file optional" for="ask_for_money_photo">
            <%= image_tag 'photo.png', height: 40 %></label>
          <p class="left">Envoyer une image (opt)</p>
          <input class="hidden file optional" type="file" name="ask_for_money[photo]" id="ask_for_money_photo">
        </div>
        </div>


      <!-- description -->
      <div id="show-2" class="form-group text optional ask_for_dollar_description ">
        <textarea class="form-control text optional" placeholder="Décrit ta demande" name="ask_for_dollar[description]" id="ask_for_dollar_description"></textarea>
      </div>


      <!-- inputs -->
      <div id="show-2" class="row ">
        <input type="submit" name="commit" value="ask" class="btn btn-large btn-floating right btn-floating green accent-3" data-disable-with="Create Ask for money">
      </div>

    <% end %>
  </div>
</div>

app/views/ask_for_dollars/edit.html.erb
<h1>Editing Ask For Dollar</h1>

<%= render 'form', ask_for_dollar: @ask_for_dollar %>

<%= link_to 'Show', @ask_for_dollar %> |
<%= link_to 'Back', ask_for_dollars_path %>

app/views/ask_for_dollars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ask For Dollars</h1>

<table>
  <thead>
    <tr>
      <th>Credit</th>
      <th>Description</th>
      <th>Object</th>
      <th>Accepted</th>
      <th>Has been reed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ask_for_dollars.each do |ask_for_dollar| %>
      <tr>
        <td><%= ask_for_dollar.credit %></td>
        <td><%= ask_for_dollar.description %></td>
        <td><%= ask_for_dollar.object %></td>
        <td><%= ask_for_dollar.accepted %></td>
        <td><%= ask_for_dollar.has_been_reed %></td>
        <td><%= link_to 'Show', kid_ask_for_dollar_path(@kid, ask_for_dollar) %></td>
        <td><%= link_to 'Edit', edit_kid_ask_for_dollar_path(@kid, ask_for_dollar) %></td>
        <td><%= link_to 'Destroy',  kid_ask_for_dollar_path(@kid, ask_for_dollar), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ask For Dollar', new_kid_ask_for_dollar_path(@kid) %>

app/views/ask_for_dollars/new.html.erb
<div class="container-ask">
  <div class="background-circle">

  </div>
  <div class="ask-container">
    <div class="row">

      <p class="left" style="font-size: 30px" >AskMoney</p>
    </div>

    <%= simple_form_for @ask_for_dollar, url: kid_ask_for_dollars_path(@membre) do |f| %>
      <div id="show-1">
        <!-- Crédit -->
        <div class="input-field form-group string optional ask_for_dollar_credit">
          <label class="control-label string optional" for="ask_for_money_credit">De combien as-tu besoin?</label>
          <input class="form-control string optional" type="text" name="ask_for_dollar[credit]" id="ask_for_dollar_credit">
        </div>
        <!-- Objet -->
        <div class="input-field form-group string optional ask_for_dollar_object">
          <label class="control-label string optional" for="ask_for_dollar_object">Pour acheter quoi ? </label>
          <input class="form-control string optional" type="text" name="ask_for_dollar[object]" id="ask_for_dollar_object">
        </div>
      </div>
      <!-- add photo -->


      <!-- description -->
      <div id="show-2" class="form-group text optional ask_for_dollar_description hidden">
        <textarea class="form-control text optional" placeholder="Décrit ta demande" name="ask_for_dollar[description]" id="ask_for_dollar_description"></textarea>
      </div>


      <!-- inputs -->
      <div id="show-2" class="row hidden">
        <input type="submit" name="commit" value="ask" class="btn btn-large btn-floating right btn-floating green accent-3" data-disable-with="Create Ask for money">

        <div class="back left come-back">
          <i class="material-icons">arrow_left</i>Retour
        </div>
      </div>

      <a id="show-1" class=" btn-floating btn-large waves-effect waves-light right black">
        <i class="material-icons">chevron_right</i>
      </a>

    <% end %>
  </div>
</div>

app/views/ask_for_dollars/new.js.erb
jQuery(document).ready(function($) {
  var modal = $("<%= escape_javascript(render 'ask_for_dollars/new') %>");

  modal.appendTo("body").animate(
    {
      top: 0
    },
    200
  );

  $(".waves-light").click(function() {
    $(".hidden").removeClass("hidden");
    $("#show-1").addClass("hidden");
  });
  $(".come-back").click(function() {
    $(this).hide();
    $(".hidden").removeClass("hidden");
    $("#show-2").addClass("hidden");
  });
});

app/views/ask_for_dollars/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row">
    <div class="ask-title">
      <h2>La demandes de <%= @membre.fisrt_name %></h2>
    </div>
  </div>

  <div class="ask-card z-depth-3">
    <!-- picture -->
    <%= image_tag 'livres.jpg', class: "ask-picture"%>

    <!-- OBJET  -->
    <div class="ask-object">
      <h5><%= @ask_for_dollar.object.capitalize %></h5>
    </div>
    <!-- CREDIT -->
    <div class="ask-credit">
     <h5><%= @ask_for_dollar.credit %>€</h5>
    </div>

  </div>
  <!-- DESCRIPTION -->
  <div class="row ask-description">
    <div class="ask-description1 col s2">
      <h6>Description:</h6>
    </div>
    <div class="ask-description2 col s12">
      <h6 style="color: black; text-align: left;">
        <%= @ask_for_dollar.description %>
      </h6>
    </div>
  </div>
</div>

<% if @ask_for_dollar.accepted? %>
  Votre Demande à été accetpée
  <% else %>

  <%= simple_form_for @ask_for_dollar, url: edit_kid_ask_for_dollar_path(@membre) do |f| %>

      <div id="accepted" class="row">

        <input type="hidden" name="ask_for_dollar[accepted]" value="">

        <div class="offset-s1 z-depth-2 ask-answer col s4">
          <span class="radio">
            <label for="ask_for_dollar_accepted_true">
              <input class="radio_buttons optional" type="radio" value="true" name="ask_for_dollar[accepted]" id="ask_for_dollar_accepted_true">
              <i class="material-icons">check</i>
              <p>J'accepte</p>
            </label>
          </span>
        </div>
        <div class="col s1"></div>

        <div class="z-depth-2 ask-answer col s4">
          <span class="radio">
            <label for="ask_for_dollar_accepted_false">
              <input class="radio_buttons optional" readonly="readonly" type="radio" value="false" name="ask_for_dollar[accepted]" id="ask_for_dollar_accepted_false">
              <p>Je refuse</p>
              <i class="material-icons">clear</i>
            </label>
          </span>
        </div>
        <div class="right" style="margin-top: 50px; margin-right: 40px;" id="show-3" >
          <button class="btn waves-effect waves-light" type="submit" name="commit">Envoyer
            <i class="material-icons right" data-disable-with="Create Ask for money">send</i>
          </button>
        </div>
      </div>
  <% end %>
<% end %>
<%= render 'shared/navbar-kids' %>