config/routes.rb
Rails.application.routes.draw do


  get 'transferts/new'

  devise_for :users
  root to: 'pages#home'

  resources :pages do
    get 'compte'
    get 'compoteste'
    resources :services
      resources :membres do
        get 'addphoto'
        get 'bravo'
        get 'profilecreation'
        get 'adressedelivraison'
        resources :paiements
        resources :pockets
        resources :transferts
      end
  end
  resources :kids do
    resources :pay4mes
    resources :ask_for_dollars
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask_for_dollar.rb
class AskForDollar < ApplicationRecord
  belongs_to :membre
  # mount_uploader :photo, PhotoUploader

end

app/models/ask_for_money.rb
class AskForMoney < ApplicationRecord
  belongs_to :membre
  mount_uploader :photo, PhotoUploader
end

app/models/ask_service.rb
class AskService < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :membre
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :family_pockets
  has_many :pockets, through: :family_pockets

  has_many :user_families

end

app/models/family_poche.rb
class FamilyPoch < ApplicationRecord
  belongs_to :family
  belongs_to :poch
end

app/models/family_pocket.rb
class FamilyPocket < ApplicationRecord
  belongs_to :family
  belongs_to :pocket
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :user_members
  has_many :members, throug: :user_members
end

app/models/membre.rb
class Membre < ApplicationRecord
  has_many :user_membres
  has_many :users, through: :user_membres

  has_many :membre_paiements
  has_many :paiements, through: :membre_paiements

  has_many :transferts
  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :ask_for_dollars

  has_many :ask_services
  has_many :services, through: :ask_services

  mount_uploader :photo, PhotoUploader

  MOIS = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"]

  def name
    fisrt_name
  end
end

app/models/membre_paiement.rb
class MembrePaiement < ApplicationRecord
  belongs_to :membre
  belongs_to :paiement
end

app/models/paiement.rb
class Paiement < ApplicationRecord
  has_many :membre_paiements
  has_many :membres, through: :membre_paiements


end

app/models/poch.rb
class Poch < ApplicationRecord

  has_many :family_pochs
  has_many :families, through: :family_pochs

end

app/models/poche.rb
class Poche < ApplicationRecord
  has_many :family_poches

end

app/models/pocket.rb
class Pocket < ApplicationRecord
  has_many :family_pockets
  has_many :user_pockets
  has_many :transferts


end

app/models/service.rb
class Service < ApplicationRecord
  has_many :ask_services
  has_many :users, through: :ask_services
  has_many :membres, through: :ask_services

  HOUR = Time.now.hour.to_s
  MINUTE = Time.now.min.to_s

end

app/models/transfert.rb
class Transfert < ApplicationRecord
  belongs_to :user
  belongs_to :membre
  belongs_to :pocket

  FREQUENCES = ["Par mois", "Par semaine", "Par jours"]
  validates :frequence, inclusion: {in: FREQUENCES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_families
  has_many :families, through: :user_families

  has_many :user_membres
  has_many :membres, through: :user_membres

  has_many :user_pockets
  has_many :pockets, through: :user_pockets

  has_many :transferts

  has_many :ask_services
  has_many :services, through: :ask_services

end

app/models/user_family.rb
class UserFamily < ApplicationRecord
  belongs_to :user
  belongs_to :family
end

app/models/user_member.rb
class UserMember < ApplicationRecord
  belongs_to :user
  belongs_to :member
end

app/models/user_membre.rb
class UserMembre < ApplicationRecord
  belongs_to :user
  belongs_to :membre
end

app/models/user_pocket.rb
class UserPocket < ApplicationRecord
  belongs_to :user
  belongs_to :pocket
  belongs_to :membre
end

app/controllers/paiements_controller.rb
class PaiementsController < ApplicationController

  # GET /paiements
  # GET /paiements.json
  def index
  end

  # GET /paiements/1
  # GET /paiements/1.json
  def show
    @membre = Membre.find(params[:membre_id])
    @paiement = Paiement.find(params[:id])
  end

  # GET /paiements/new
  def new
    @membre = Membre.find(params[:membre_id])
    @paiement = Paiement.new
  end

  # GET /paiements/1/edit
  def edit
    @paiement = Paiement.find(params[:id])
    @membre = Membre.find(params[:membre_id])
  end

  # POST /paiements
  # POST /paiements.json
  def create
    @paiement = Paiement.new(paiement_params)
    @membre = Membre.find(params[:membre_id])
    @mp = MembrePaiement.new
    @mp.membre = @membre
    @mp.paiement = @paiement

    if @paiement.save && @mp.save
      redirect_to page_membre_profilecreation_path(current_user, @membre)
    else
      render :new
    end

  end

  # PATCH/PUT /paiements/1
  # PATCH/PUT /paiements/1.json
  def update
    @paiement = Paiement.find(params[:id])
    @membre = Membre.find(params[:membre_id])
    respond_to do |format|
      if @paiement.update(paiement_params)
        format.html { redirect_to page_membre_path(@membre), notice: 'Paiement was successfully updated.' }
        format.json { render :show, status: :ok, location: @paiement }
      else
    raise
        format.html { render :edit }
        format.json { render json: @paiement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paiements/1
  # DELETE /paiements/1.json
  def destroy
    @paiement.destroy
    respond_to do |format|
      format.html { redirect_to paiements_url, notice: 'Paiement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def paiement_params
      params.require(:paiement).permit(:roof, :plafond, :mode, :adress_1, :adress_2, :cp, :city)
    end
end

app/views/paiements/_form.html.erb
<%= simple_form_for @paiement, url: page_membre_paiements_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <!-- paiement roof -->
    <div class="form-group float optional paiement_roof">
      <label class="control-label float optional" for="paiement_roof" style="float: right; font-weight: 400; color:black;" >CE QU'IL PEUT DÉPENSER</label>
      <input class="form-control numeric float optional" placeholder="plafond maximum €" type="number" step="any" name="paiement[roof]" id="paiement_roof">
    </div>

    <!-- paiement plafond -->
    <div class="form-group select optional paiement_roof">
      <label class="control-label select optional" for="paiement_roof"></label>
      <select class="browser-default" name="paiement[plafond]" id="paiement_plafond">
        <option value="Semaine">Par semaine</option>
        <option value="Mois">Par mois</option>
        <option value="Jour">Par jour</option>
      </select>


    </div>
    <!-- paiement mode -->
    <div class="container-paiement">
      <div class="row">
        <div class="form-group check_boxes optional paiement_mode">

          <label class="col-xs-12" style="padding-left: 23%; font-weight: 400; color:black;" >COMMENT PEUT-IL PAYER?</label>

          <input type="hidden" name="paiement[mode][]" value="">


              <div class="col-xs-3 mode" id="badge-mode">
                <span class="checkbox">
                  <label for="paiement_mode_applepay">
                    <input class="check_boxes optional  hidden" type="checkbox" value="ApplePay" name="paiement[mode][]" id="paiement_mode_applepay">
                    <%= image_tag 'applepay.png', height: 25 %> <h1></h1>
                  </label>
                </span>
                <p>ApplePay</p>
              </div>

              <div class="col-xs-3 mode" id="badge-mode">
                <span class="checkbox">
                  <label for="paiement_mode_paylib" >
                    <input class="check_boxes optional  hidden" type="checkbox" value="PayLib" name="paiement[mode][]" id="paiement_mode_paylib"><%= image_tag 'paylib.png', height: 30 %> <h1></h1>
                  </label>
                </span>
                <p>PayLib</p>
              </div>

              <div class="col-xs-3 mode" id="badge-mode-3">
                <span class="checkbox">
                  <label for="paiement_mode_cb">
                    <input class="check_boxes optional hidden" type="checkbox" value="CB" name="paiement[mode][]" id="paiement_mode_cb">
                    <%= image_tag 'card.png', height: 30 %> <h1></h1>
                  </label>
                </span>
                <p>Carte</p>
              </div>

            </div>
          </div>
        </div>
    </div>
        <!-- Transfert Adresse -->
        <div class="adresse-container hidden">
          <p style="margin-top: 80px;" >Entrez une adresse de livraison pour recevoir une carte, celle-ci sera à son nom.</p>

          <div class="form-group string optional paiement_adress_1">
            <label class="control-label string optional" for="paiement_adress_1"></label>
            <input class="form-control string optional" placeholder="Adress line 1" type="text" name="paiement[adress_1]" id="paiement_adress_1">
          </div>

          <div class="form-group string optional paiement_adress_2">
            <label class="control-label string optional" for="paiement_adress_2"></label>
            <input class="form-control string optional" placeholder="Adress line 2" type="text" name="paiement[adress_2]" id="paiement_adress_2">
          </div>

          <div class="row">

            <div class="col-xs-6">
              <div class="form-group string optional paiement_cp">
                <label class="control-label string optional" for="paiement_cp"></label>
                <input class="form-control string optional" placeholder="Code postal" type="text" name="paiement[cp]" id="paiement_cp">
              </div>
            </div>



            <div class="col-xs-6">
              <div class="form-group string optional paiement_city">
                <label class="control-label string optional" for="paiement_city"></label>
                <input class="form-control string optional" placeholder="Ville" type="text" name="paiement[city]" id="paiement_city">
              </div>
            </div>

          </div>

        </div>

      <div class="row">
        <div class="btn-container" id="btn-container-paiement">
          <%= f.submit "VALIDER", class: 'btn-form' %>
        </div>
      </div>
<% end %>

app/views/paiements/edit.html.erb
<div class="grey-b">

  <div class="header-profilecreation">
    <div class="col s10">
      <div class="header-profilecreation-name">
       <h4><%= @membre.fisrt_name %>Raphael</h4>
      </div>
    </div>
    <div class="header-profilecreation-photo col s2">
      <%= image_tag 'teen.jpg', height: 40, width: 40, class: "img-circle"%>
    </div>

  </div>

  <div class="container-poche-creation">
    <div style="margin: 0 auto" id="test1" class="pocket">
      <div class="pocket-name" >
        <p></p>
      </div>
      <div class="container-pocket-pics">
        <div class="right pocket-pics">
          <p></p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="main-container-profilecreation">
  <div class="content-profilecreation">
    <h3 style="margin: 20px;
    font-size: 20px;" >Créez lui sa première poche</h3>
    <h5>Vous donnez de l'argent régulièrement à <%= @membre.fisrt_name %>, permettez lui de gérer son argent en toutes autonomie</h5>
    <%= simple_form_for @pocket, url: page_membre_pockets_path(@user, @membre) do |f| %>
      <div class="form-group string optional pocket_name">

        <input class="form-control string optional" placeholder="D'abord, donnez un nom à cette poche" type="text" name="pocket[name]" id="pocket_name">
      </div>
      <div class="row">
        <div class="hidden btn-container">
          <%= f.submit "Ajouter la poche" %>
        </div>
      </div>
      <% end %>

      <div class="center" id="value-range" >
        <p>40€</p>
      </div>
      <div class="range-container">
        <p class="range-field col-xs-12 my-range">
          <input aria-required="true" name="transfert[value]" type="range" id="test3" min="0" max="250" />
        </p>
      </div>

      <div class="row">


        <div class="col s12">
          <div class="form-group select optional transfert_frequence">
            <select class="form-control select optional" name="transfert[frequence]">
              <option value="Par mois">Tous les 1er du mois</option>
              <option value="Par semaine">Tous les débuts de semaines</option>
              <option value="Par jours">Tous les jours</option>
            </select>
          </div>
        </div>
      </div>

  </div>

  <div style="bottom: -40px;" class="footer-buttons">
    <div class="right" >
      <a href="bravo" class=" btn-floating btn-large waves-effect waves-light black">
        <i class="material-icons">arrow_forward</i>
      </a>

    </div>
    <div class="left">
      <a href="javascript:history.back()">
        <i class="material-icons">arrow_back</i>retour
      </a>

    </div>
  </div>

</div>

<div class="main-container-profilecreation">

  <div class="header-profilecreation">
      <p>&#x2501; &nbsp;<%=@membre.fisrt_name%>&nbsp;  &#x2501;</p>
      <div class="chip left">
      <%= image_tag 'pomme.png' %>
      Pay
    </div>
    <div class="chip left">
      <%= image_tag 'mastercard.png'%>
      carte débit
    </div>
  </div>
  <div class="content-profilecreation">
    <h4>Choisisez ce qu'il peut dépenser</h4>
    <%= simple_form_for @paiement, url: page_membre_paiement_path(@membre) do |f| %>
    <%= f.error_notification %>

    <!-- Range Roof -->
      <div class="range-container">
          <p class="range-field col-xs-12 my-range">
            <input aria-required="true" name="paiement[roof]" type="range" id="test3" min="0" max="250" />
          </p>

      </div>
    <!-- Plafond -->
      <div class="row">
        <div class="col-xs-12">
          <select class="my-plafond form-control optional" name="paiement[plafond]" id="paiement_plafond">
            <option selected="selected" value="Mois">Mois</option>
            <option value="Semaine">Semaine</option>
            <option value="Jour">Jour</option>
          </select>
        </div>
      </div>



  </div>

  <div class="footer-buttons">
    <div class="btn-floating right btn-large waves-effect waves-light black add" >
    <input type="submit" name="commit" value="&#x2794">

    </div>

    <a href="javascript:history.back()">
      <i class="material-icons">arrow_back</i>retour
    </a>
  </div>

    <% end %>
</div>

app/views/paiements/index.html.erb
<div class="container-congrat">
  <div class="header-congrat">
    <div class="congrat-pics">
      <%= image_tag 'ado.jpg', class: 'congrat-pics' %>
    </div>
    <div class="text-congrat">
      <h1>Bravo ! <br> Le compte de <%= Membre.last.fisrt_name %> à été crée !</h1>
    </div>
  </div>

  <div class="congrat-phone">

    <div class="form-group string optional membre_fisrt_name">
      <label class="control-label string optional" for="membre_fisrt_name">Rentrez son numéro de téléphone <br> pour qu'il puisse se connecter à l'application</label>
      <input class="form-control string optional" placeholder="+33 6 xx xx xx xx" type="text" name="membre[fisrt_name]" id="membre_fisrt_name">
    </div>

    <div class="row">
      <div class="btn-container">
        <div class="btn-form">
        <%= link_to 'ENVOYER', page_membres_path(current_user), class: 'envoie'%>
        </div>
      </div>
    </div>

  </div>


</div>

app/views/paiements/new.html.erb
<div class="grey-b">

  <div class="header-profilecreation">
    <div class="col s10">
      <div class="header-profilecreation-name">
       <h4><%= @membre.fisrt_name %>Raphael</h4>
      </div>
    </div>
    <div class="header-profilecreation-photo col s2">
      <%= image_tag 'teen.jpg', height: 40, width: 40, class: "img-circle"%>
    </div>

  </div>

  <div class="container-poche-creation">
    <div style="margin: 0 auto" id="test1" class="pocket">
      <%= image_tag 'visa-card.png', class: 'vise-pics' %>
    </div>
  </div>
</div>


<div class="main-container-profilecreation">
  <div class="content-profilecreation">
    <h3 style="margin: 20px;
    font-size: 20px;" >Paramétrez son moyen de paiement</h3>
    <h5>Ceci est la carte de paiement avec la quelle Raphael pourra payer. <br> Rassurez vous, vous avez les controlle sur l'utilisation de la carte!</h5>
    <%= simple_form_for @paiement, url: page_membre_paiements_path  do |f| %>




      <div class="center" id="value-range" >
        <p>40€</p>
      </div>
      <div class="range-container">
        <p class="range-field col-xs-12 my-range">
          <input aria-required="true" name="transfert[value]" type="range" id="test3" min="0" max="250" />
        </p>
      </div>
      <div class="row">
        <div class="col s12">
          <div class="form-group select optional transfert_frequence">
            <select class="form-control select optional" name="transfert[frequence]">
              <option value="Par mois">Tous les 1er du mois</option>
              <option value="Par semaine">Tous les débuts de semaines</option>
              <option value="Par jours">Tous les jours</option>
            </select>
          </div>
        </div>
      </div>

      <% end %>


  <div style="bottom: -40px;" class="footer-buttons">
    <div class="right" >
      <a href="../profilecreation" class=" btn-floating btn-large waves-effect waves-light black">
        <i class="material-icons">arrow_forward</i>
      </a>

    </div>
    <div class="left">
      <a href="javascript:history.back()">
        <i class="material-icons">arrow_back</i>retour
      </a>
    </div>

</div>

app/views/paiements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roof:</strong>
  <%= @paiement.roof %>
</p>

<p>
  <strong>Plafond:</strong>
  <%= @paiement.plafond %>
</p>

<p>
  <strong>Mode:</strong>
  <%= @paiement.mode %>
</p>

<p>
  <strong>Adress 1:</strong>
  <%= @paiement.adress_1 %>
</p>

<p>
  <strong>Adress 2:</strong>
  <%= @paiement.adress_2 %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @paiement.cp %>
</p>

<p>
  <strong>City:</strong>
  <%= @paiement.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @paiement.country %>
</p>

<%= link_to 'Edit', edit_paiement_path(@paiement) %> |
<%= link_to 'Back', paiements_path %>